
-- =============================================================================
-- LocDailyMar 27.2.0
-- PUBLIC CHECKOUT + DELIVERY EMAIL/WHATSAPP
-- Jalankan pada Supabase PROJECT LICENSE AUTHORITY V2.
-- =============================================================================
begin;

create table if not exists public.ldm2_checkout_deliveries (
    payment_id uuid primary key
        references public.ldm2_payments(id) on delete cascade,
    license_id uuid not null
        references public.ldm2_licenses(id) on delete restrict,
    order_id text not null unique,
    public_status_token_hash text not null,
    license_key_ciphertext text not null,

    email_status text not null default 'pending'
        check (email_status in ('pending','sent','failed','not_configured')),
    whatsapp_status text not null default 'pending'
        check (whatsapp_status in ('pending','sent','failed','not_configured')),
    provision_status text not null default 'pending'
        check (provision_status in ('pending','ready','failed','not_configured')),

    email_message_id text,
    whatsapp_message_id text,
    email_attempts integer not null default 0 check (email_attempts >= 0),
    whatsapp_attempts integer not null default 0 check (whatsapp_attempts >= 0),
    email_error text,
    whatsapp_error text,
    provision_error text,

    owner_user_id uuid,
    last_attempt_at timestamptz,
    completed_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists idx_ldm2_checkout_delivery_license
on public.ldm2_checkout_deliveries(license_id,created_at desc);

create index if not exists idx_ldm2_checkout_delivery_status
on public.ldm2_checkout_deliveries(email_status,whatsapp_status,provision_status);

drop trigger if exists trg_ldm2_checkout_deliveries_touch
on public.ldm2_checkout_deliveries;
create trigger trg_ldm2_checkout_deliveries_touch
before update on public.ldm2_checkout_deliveries
for each row execute function public.ldm2_touch_updated_at();

alter table public.ldm2_checkout_deliveries enable row level security;
revoke all on public.ldm2_checkout_deliveries from anon, authenticated;

-- Rate limit checkout publik. Hanya hash fingerprint yang disimpan.
create table if not exists public.ldm2_checkout_attempts (
    id bigint generated by default as identity primary key,
    fingerprint_hash text not null,
    order_id text,
    created_at timestamptz not null default now()
);

create index if not exists idx_ldm2_checkout_attempts_fingerprint_time
on public.ldm2_checkout_attempts(fingerprint_hash,created_at desc);

alter table public.ldm2_checkout_attempts enable row level security;
revoke all on public.ldm2_checkout_attempts from anon, authenticated;


-- Membuat ulang order Midtrans untuk lisensi pending_payment yang sama
-- tanpa membuat Store Code/License baru.
create or replace function public.ldm2_create_retry_purchase_order(
    p_order_id text,
    p_license_id uuid,
    p_billing_cycle text,
    p_amount bigint
)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare
    v_license public.ldm2_licenses%rowtype;
    v_cycle text := lower(btrim(p_billing_cycle));
    v_expected bigint;
    v_months integer;
    v_payment_id uuid;
begin
    if nullif(btrim(p_order_id),'') is null then raise exception 'Order ID wajib diisi.'; end if;
    select * into v_license
    from public.ldm2_licenses
    where id=p_license_id
    for update;

    if not found then raise exception 'Lisensi pending tidak ditemukan.'; end if;
    if v_license.status<>'pending_payment' then
        raise exception 'Retry hanya tersedia untuk lisensi pending_payment.';
    end if;

    if exists(
        select 1 from public.ldm2_payments
        where license_id=v_license.id
          and status in ('pending','challenge')
    ) then
        raise exception 'Masih ada order pembayaran yang menunggu.';
    end if;

    v_expected := public.ldm2_expected_price(v_license.plan_code,v_cycle);
    if p_amount<>v_expected then raise exception 'Nominal retry tidak sesuai harga resmi.'; end if;
    v_months := case v_cycle when 'monthly' then 1 when 'yearly' then 12 when 'lifetime' then 0 else -1 end;
    if v_months<0 then raise exception 'Periode retry tidak valid.'; end if;

    insert into public.ldm2_payments(
        order_id,license_id,payment_type,plan_code,billing_cycle,duration_months,amount,status
    ) values (
        btrim(p_order_id),v_license.id,'purchase',v_license.plan_code,v_cycle,v_months,p_amount,'pending'
    ) returning id into v_payment_id;

    insert into public.ldm2_events(license_id,event_type,detail)
    values(v_license.id,'PAYMENT_ORDER_RETRY_CREATED',jsonb_build_object(
        'order_id',btrim(p_order_id),'billing_cycle',v_cycle,'amount',p_amount
    ));

    return jsonb_build_object(
        'ok',true,'license_id',v_license.id,'payment_id',v_payment_id,
        'order_id',btrim(p_order_id),'plan_code',v_license.plan_code,
        'billing_cycle',v_cycle,'amount',p_amount,
        'store_id',v_license.primary_store_id,'store_code',v_license.primary_store_code,
        'network_id',v_license.network_id,'status','pending'
    );
end;
$$;

revoke all on function public.ldm2_create_retry_purchase_order(text,uuid,text,bigint) from public,anon,authenticated;
grant execute on function public.ldm2_create_retry_purchase_order(text,uuid,text,bigint) to service_role;

-- Audit metadata patch.
insert into public.ldm2_events(license_id,event_type,detail)
select null,'SYSTEM_PATCH',jsonb_build_object(
    'version','27.2.0',
    'feature','PUBLIC_CHECKOUT_EMAIL_WHATSAPP',
    'installed_at',now()
)
where not exists (
    select 1 from public.ldm2_events
    where event_type='SYSTEM_PATCH'
      and detail->>'version'='27.2.0'
      and detail->>'feature'='PUBLIC_CHECKOUT_EMAIL_WHATSAPP'
);

commit;
